# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/project/lab3_risc/lab3_risc.srcs/sources_1/bd/risc32/ip/risc32_clk_wiz_0_0/risc32_clk_wiz_0_0.xci
# IP: The module: 'risc32_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/project/lab3_risc/lab3_risc.gen/sources_1/bd/risc32/ip/risc32_clk_wiz_0_0/risc32_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'risc32_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/project/lab3_risc/lab3_risc.gen/sources_1/bd/risc32/ip/risc32_clk_wiz_0_0/risc32_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'risc32_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/project/lab3_risc/lab3_risc.gen/sources_1/bd/risc32/ip/risc32_clk_wiz_0_0/risc32_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'risc32_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/project/lab3_risc/lab3_risc.srcs/sources_1/bd/risc32/ip/risc32_clk_wiz_0_0/risc32_clk_wiz_0_0.xci
# IP: The module: 'risc32_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/project/lab3_risc/lab3_risc.gen/sources_1/bd/risc32/ip/risc32_clk_wiz_0_0/risc32_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'risc32_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/project/lab3_risc/lab3_risc.gen/sources_1/bd/risc32/ip/risc32_clk_wiz_0_0/risc32_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'risc32_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/project/lab3_risc/lab3_risc.gen/sources_1/bd/risc32/ip/risc32_clk_wiz_0_0/risc32_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'risc32_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
