# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Nexys-A7-100T-Master.xdc

# Block Designs: bd/risc32/risc32.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==risc32 || ORIG_REF_NAME==risc32} -quiet] -quiet

# IP: bd/risc32/ip/risc32_adder_0_0/risc32_adder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==risc32_adder_0_0 || ORIG_REF_NAME==risc32_adder_0_0} -quiet] -quiet

# IP: bd/risc32/ip/risc32_xlconstant_0_0/risc32_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==risc32_xlconstant_0_0 || ORIG_REF_NAME==risc32_xlconstant_0_0} -quiet] -quiet

# IP: bd/risc32/ip/risc32_regfile_0_0/risc32_regfile_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==risc32_regfile_0_0 || ORIG_REF_NAME==risc32_regfile_0_0} -quiet] -quiet

# IP: bd/risc32/ip/risc32_slice_inst_0_0/risc32_slice_inst_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==risc32_slice_inst_0_0 || ORIG_REF_NAME==risc32_slice_inst_0_0} -quiet] -quiet

# IP: bd/risc32/ip/risc32_alu32_0_0/risc32_alu32_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==risc32_alu32_0_0 || ORIG_REF_NAME==risc32_alu32_0_0} -quiet] -quiet

# IP: bd/risc32/ip/risc32_MUX_32b_2_to_1_0_0/risc32_MUX_32b_2_to_1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==risc32_MUX_32b_2_to_1_0_0 || ORIG_REF_NAME==risc32_MUX_32b_2_to_1_0_0} -quiet] -quiet

# IP: bd/risc32/ip/risc32_xlconstant_1_0/risc32_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==risc32_xlconstant_1_0 || ORIG_REF_NAME==risc32_xlconstant_1_0} -quiet] -quiet

# IP: bd/risc32/ip/risc32_xlconstant_1_1/risc32_xlconstant_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==risc32_xlconstant_1_1 || ORIG_REF_NAME==risc32_xlconstant_1_1} -quiet] -quiet

# IP: bd/risc32/ip/risc32_concat_imm_0_0/risc32_concat_imm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==risc32_concat_imm_0_0 || ORIG_REF_NAME==risc32_concat_imm_0_0} -quiet] -quiet

# IP: bd/risc32/ip/risc32_dmem_0_0/risc32_dmem_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==risc32_dmem_0_0 || ORIG_REF_NAME==risc32_dmem_0_0} -quiet] -quiet

# IP: bd/risc32/ip/risc32_MUX_32b_2_to_1_1_0/risc32_MUX_32b_2_to_1_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==risc32_MUX_32b_2_to_1_1_0 || ORIG_REF_NAME==risc32_MUX_32b_2_to_1_1_0} -quiet] -quiet

# IP: bd/risc32/ip/risc32_MUX_5b_2_to_1_0_0/risc32_MUX_5b_2_to_1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==risc32_MUX_5b_2_to_1_0_0 || ORIG_REF_NAME==risc32_MUX_5b_2_to_1_0_0} -quiet] -quiet

# IP: bd/risc32/ip/risc32_cancat_control_0_0/risc32_cancat_control_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==risc32_cancat_control_0_0 || ORIG_REF_NAME==risc32_cancat_control_0_0} -quiet] -quiet

# IP: bd/risc32/ip/risc32_control_rom_0_0/risc32_control_rom_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==risc32_control_rom_0_0 || ORIG_REF_NAME==risc32_control_rom_0_0} -quiet] -quiet

# IP: bd/risc32/ip/risc32_imem_0_0/risc32_imem_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==risc32_imem_0_0 || ORIG_REF_NAME==risc32_imem_0_0} -quiet] -quiet

# IP: bd/risc32/ip/risc32_MUX_20b_2_to_1_0_0/risc32_MUX_20b_2_to_1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==risc32_MUX_20b_2_to_1_0_0 || ORIG_REF_NAME==risc32_MUX_20b_2_to_1_0_0} -quiet] -quiet

# IP: bd/risc32/ip/risc32_segment_0_0/risc32_segment_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==risc32_segment_0_0 || ORIG_REF_NAME==risc32_segment_0_0} -quiet] -quiet

# IP: bd/risc32/ip/risc32_clk_wiz_0_0/risc32_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==risc32_clk_wiz_0_0 || ORIG_REF_NAME==risc32_clk_wiz_0_0} -quiet] -quiet

# IP: bd/risc32/ip/risc32_pc_0_0/risc32_pc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==risc32_pc_0_0 || ORIG_REF_NAME==risc32_pc_0_0} -quiet] -quiet

# XDC: e:/project/lab3_risc/lab3_risc.gen/sources_1/bd/risc32/risc32_ooc.xdc
